import json

original = [
    "what is the fee for btech in computer science?",
    "what is the sc category discount for diploma in mechanical engineering?",
    "what is the email id of the vice chancellor?",
    "what is the eligibility for ug programs?",
    "is bba supply chain management available at dwarka campus?",
    "what is the total fee for mca?",
    "do you have aerospace engineering?",
    "what awards do i get if i exit after 2 years in bca?",
    "where is the rajokri campus located?",
    "is diploma in architecture available for girls only?",
    "what is the first semester fee for bsc physical sciences?",
    "can i do pg diploma in ai if i did ba in history?",
    "what is the date for online registration?",
    "who is the director of academics?",
    "what courses are there after 10th?",
    "what courses are there after 12th science?",
    "what pg courses are available?",
    "is there any nursing program?",
    "what are the courses in computer applications?",
    "is fashion design offered?",
    "what is the caution money amount?",
    "what is the fee for b.tech first year?",
    "how to apply for btech registration?",
    "what are the campuses for diploma in pharmacy?",
    "what is the sc fee for bba retail management?",
    "what is the sc fee for pg diploma in software engineering?",
    "is phd available in computer science?",
    "what is the email of okhla campus director?",
    "what is the fee for environmental science?",
    "what exit awards are available for retail management?",
    "is there a hostel discount?",
    "do you have any medical courses like mbbs?",
    "what is the eligibility for btech?",
    "what is the fee for diploma in computer engineering?",
    "what is the fee for integrated btech mtech?",
    "is there a law degree?",
    "what are the campuses for pg courses?",
    "what are the ug certificate courses?",
    "what is the duration of bca?",
    "what is the fee for an international student?",
    "how much is the enrolment fee?"
]

bilingual = [
    "bhai btech cse ka first sem fee kya hai?",
    "sir mechanical diploma karni hai, sc quota me discount kitna milega aur final fees kya hogi?",
    "vice chancellor sir ka email id dedo",
    "ug programs me admission lene ke liye eligibility criteria kya hai?",
    "dwarka wale campus me bba supply chain hai kya?",
    "mca ka total course fee bata do yar",
    "kya dseu me aerospace engineering offer hoti hai?",
    "bca start karne ke baad agar 2 saal me exit maru toh kaunsa award ya certificate milega?",
    "rajokri campus exactly kahan par hai?",
    "architecture ka diploma sirf girls ke liye hai kya?",
    "bsc physical sciences first sem ka fee structure bhej do",
    "maine ba history kiya hai, kya main ai me pg diploma kar sakta hu?",
    "online registration kab se start ho rahe hain?",
    "academics director kaun hai yahan ka?",
    "10th paas ki hai abhi, kaun kaun se course kar sakta hu?",
    "12th science wale students ke liye kya options hain?",
    "pg yani post grad ke kya kya courses hain?",
    "kya aapke paas koi nursing program hai?",
    "computer applications se related sabhi courses batao",
    "fashion design wala course karwaya jata hai kya?",
    "caution money kitni deni hoti hai admission time pe?",
    "btech first year ka total kharcha kitna aayega?",
    "btech me admission ke liye registration kaise karni hai?",
    "diploma pharmacy kaun kaun se campuses me available hai?",
    "bba retail management ki fee batao agar sc category ho",
    "pg diploma software engineering sc category fees",
    "computer science me phd ho jayegi kya dseu se?",
    "okhla campus director ko email karna hai, id kya hai?",
    "environmental science course ka fees kitna lagta hai?",
    "retail management me exit options aur unke awards batao",
    "hostel fee me koi discount ya rebate milta hai kya?",
    "mbbs jaisa koi medical course hai dseu me?",
    "btech karna hai toh 12th me kitne marks chahiye eligibility ke liye?",
    "diploma computer engineering ka admission fees kitna hai?",
    "integrated btech mtech program ka fees structure kya hai?",
    "mujhe law padhni hai, degree milegi kya?",
    "pg courses kaun kaun se campus me padhaye jate hain?",
    "ug certificate level ke kon se courses hain?",
    "bca course total kitne saal ka hota hai?",
    "international aur foreign students ka fee kitna hota hai?",
    "admission ke time enrolment fee kitni pay karni hai?"
]

with open("bilingual_test_queries.json", "w") as f:
    json.dump(bilingual, f, indent=4)
print("Saved 41 bilingual queries to bilingual_test_queries.json")
